const ResourceType = {
    BRIDGE: 'bridge',
    DEVICE: 'device',
    //BEHAVIOR_SCRIPT: 'behavior_script',
    //BEHAVIOR_INSTANCE: 'behavior_instance',
    //GEOFENCE_CLIENT: 'geofence_client',
    //GEOLOCATION: 'geolocation',
    //SMART_SCENE: 'smart_scene',
    CLIP: 'clip',
    //BRIDGE_HOME: 'bridge_home',
    //GROUPED_LIGHT: 'grouped_light',
    //GROUPED_LIGHT_LEVEL: 'grouped_light_level',
    //GROUPED_MOTION: 'grouped_motion',
    //ROOM: 'room',
    //SERVICE_GROUP: 'service_group',
    //ZONE: 'zone',
    //SCENE: 'scene',
    //HOMEKIT: 'homekit',
    //BUTTON: 'button',
    //DEVICE_POWER: 'device_power',
    //DEVICE_SOFTWARE_UPDATE: 'device_software_update',
    //ENTERTAINMENT: 'entertainment',
    //LIGHT: 'light',
    //LIGHT_LEVEL: 'light_level',
    //ZIGBEE_CONNECTIVITY: 'zigbee_connectivity',
    //ZGP_CONNECTIVITY: 'zgp_connectivity',
    //MOTION: 'motion',
    //CAMERA_MOTION: 'camera_motion',
    //RELATIVE_ROTARY: 'relative_rotary',
    //TEMPERATURE: 'temperature',
    //ZIGBEE_DEVICE_DISCOVERY: 'zigbee_device_discovery',
    //CONTACT: 'contact',
    //TAMPER: 'tamper',
    //SPEAKER: 'speaker',
    //BELL_BUTTON: 'bell_button',
    MATTER: 'matter',
    //MATTER_FABRIC: 'matter_fabric',
    //ENTERTAINMENT_CONFIGURATION: 'entertainment_configuration'
};

export default ResourceType;